language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

services:
  - redis-server

sudo: false
dist: trusty

matrix:
  allow_failures:
    - php: nightly

before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi"
  - composer update

script:
  - $TRAVIS_BUILD_DIR/vendor/phpunit/phpunit/phpunit
